#####################################
###         PalladiumPool         ###
###           by SyphiX           ###
### https://github.com/SyphiX897  ###
#####################################

enabled_worlds: "world;world_the_end"
disabled_worlds: "world_nether"
regions: "afk;afk2"

pool:
  interval: 300 #seconds
  enter_pool:
    title:
      enabled: true
      text: "<gradient:dark_green:green>You have entered the pool"
    actionBar:
      enabled: true
      text: "<gradient:dark_green:green>You have entered the pool"
    message:
      enabled: true
      text: "<gradient:dark_green:green>You have entered the pool"
  leave_pool:
    title:
      enabled: true
      text: "<gradient:dark_green:green>You have left the pool"
    actionBar:
      enabled: true
      text: "<gradient:dark_green:green>You have left the pool"
    message:
      enabled: true
      text: "<gradient:dark_green:green>You have left the pool"

  reward:
    money:
      enabled: true
      amount: "100-200"
    crate:  # Supported plugins: ExcellentCrates, EcoCrate, CrazyCrate
      enabled: true
      keys: # "name;amount;chance"
        - "common;2;50%"
        - "rare;1;25%"
    item: # Supported plugin: Slimefun
      enabled: true
      items: # "name;amount;chance"
        - "DIAMOND;3;25%"